# Gitpod configuration file for Ejabberd using the latest Erlang/OTP image
image: erlang:latest

tasks:
  - init: |
      # Install necessary dependencies
      apt-get update && apt-get install -y \
        build-essential \
        libexpat1-dev \
        libyaml-dev \
        curl \
        wget \
        autoconf \
        automake \
        libssl-dev &&
      apt-get clean &&
      # Clone and build Ejabberd
      git clone https://github.com/ejabberd/ejabberd.git &&
      cd ejabberd &&
      ./autogen.sh &&
      ./configure &&
      make &&
      make install &&
      ejabberdctl start
    command: ejabberdctl debug

ports:
  - port: 5222
    visibility: public
    onOpen: ignore
  - port: 5280
    visibility: public
    onOpen: open-preview

vscode:
  extensions:
    - esbenp.prettier-vscode
    - pgourlain.erlang
