image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      echo "Gitpod container with Erlang and Ejabberd built."
    command: ejabberdctl debug

ports:
  - port: 5222
    visibility: public
    onOpen: ignore
  - port: 5280
    visibility: public
    onOpen: open-preview

vscode:
  extensions:
    - esbenp.prettier-vscode
    - pgourlain.erlang
